export interface ApplyResponse {
  ok: boolean;
  errors: any[];
  person: {
    id: number;
    name: string;
    profile_picture_thumb_url: string;
    profile_picture_original_url: string;
    description: string | null;
    emails: string[];
    phones: string[];
    job_profiles: any[];
    education_profiles: any[];
    documents: any[];
    resumes: string[];
    custom_text_1: string | null;
    custom_text_2: string | null;
    custom_text_3: string | null;
    custom_text_4: string | null;
    custom_hierarchy_1: any[];
    custom_text_5: string | null;
    custom_hierarchy_2: any[];
    custom_hierarchy_3: any[];
    custom_hierarchy_4: any[];
    custom_hierarchy_5: any[];
    custom_hierarchy_6: any[];
    candidate_jobs: any[];
    linkedin_url: string;
    person_global_status: null;
    all_raw_tags: string;
    agency_id: number | null;
    blocked: boolean;
    blocked_until: string | null;
    list_ids: any[];
    candidates: any[];
    skillsets: string | null;
    owned_by_id: string | null;
    compensation: string | null;
    compensation_notes: string | null;
    compensation_currency_id: string | null;
    salary: string | null;
    salary_type_id: string | null;
    target_salary: string | null;
    target_salary_type_id: string | null;
    bonus: string | null;
    equity: string | null;
    bonus_type_id: string | null;
    equity_type_id: string | null;
    bonus_payment_type_id: string | null;
    created_at: string;
    updated_at: string;
    created_by_id: string | null;
    updated_by_id: string | null;
    person_shares: any[];
    person_types: any[];
    location: string | null;
    address: string | null;
    city: string | null;
    state: string | null;
    zip: string | null;
    country: string | null;
    source_type: any[];
    diversity_types: any[];
  };
}
